### ISSUE TITLE
결제 테스트 

### ISSUE THREAD

**Issue by jenniferkang** [creativecommonskorea/2015-global-summit#12]
1. https://summit.cckorea.org/register.html  
   요화면이 왜 나오는지 몰겠어요. 뒤에 나오는 화면 필드와 중복됩니다. 

2.첨부처럼 이메일 등을 잘못 입력한 경우에... 오류 메시지가 CC HQ에서 날아오는데. 
이거 그냥 HQ서버 가지 말고 HTML에서 규칙 안맞는 경우에 바로 에러  메시지 나오면 어떨런지요?
(이거 개발자분들은 무슨 이야기인지 아시겠지죠?
1. @khseo 님 결제 모두 완료한 후에.. 안내 페이지가 나오면 좋겠어요.
   메일로 안내한 내용을 쭈욱 보여주면 어떨런지요? 
2. 한가지. 텍스만 수정해 주세요. (CC후원 -) CC KOREA  정기후원 / 후원사 
3. 카드결제하는데... 비밀번호 맞는데. 자꾸 비밀번호 틀린다고 나옵니다. 확인 필요해보여요. 

![2015-09-16 10 24 58](https://cloud.githubusercontent.com/assets/11837686/9894392/5f1d661c-5c5e-11e5-8ca1-43cce70f50fe.png)
![2015-09-16 10 32 39](https://cloud.githubusercontent.com/assets/11837686/9894393/5f5e6b1c-5c5e-11e5-9adb-e0d3518b24aa.png)

부탁합니다.

**Comment by mozodev** [comment]
https://summit.cckorea.org/register.html
HQ와 주고 받은 장문의 메일 중에 포함되어 있는 내용입니다.
우선 HQ CRM에 등록한 후 이후는 우리가 주는 URL로 리다이렉트하겠다.이렇게 정리가 되서
https://summit.cckorea.org/attend.html 여기로 넘어가게 됩니다.

**Comment by soohyunpae** [comment]
방금 결제 테스트했는데요~
완료 확인 메일에 들어간 써밋 배너 이미지에는 '나비아트센터'로 들어가있어요~ @khseo 님 확인 부탁드려요~!
