### ISSUE TITLE
폴 켈러 프로그램 상세설명 업데이트

### ISSUE THREAD

**Issue by soohyunpae** [creativecommonskorea/2015-global-summit#14]
15일 오픈 지식 세션에 폴 켈러 프로그램 설명 업데이트 부탁드려요~!

https://summit.cckorea.org/session/15-track1.html

유럽연합은 수년간 Europeana.eu라는 플랫폼을 통해 유럽의 문화 콘텐츠 기관들이 보유한 문화유산을 디지털화해 누구나 열람하고 사용할 수 있도록 공개해왔다. 지금까지 공개된 총 4,300만 건의 저작물 중 25%는 퍼블릭 도메인이며 22%는 CCL 로 공개되어 있다. 오늘날 유로피아나는 오픈 데이터와 오픈 콘텐츠를 누구보다도 적극적으로 추구하는 단체다. 이 세션에서는 유로피아나가 이러한 오픈 콘텐츠의 허브가 되었는지를 소개하고, 다른 문화 유산 기관 및 플랫폼에게 도움이 될만한 경험과 교훈을 공유한다.

**Comment by jenniferkang** [comment]
이거 연사소개에서도 바꿔주시면 어때요?

2015-09-30 17:31 GMT+09:00 Yeongtaek Hong notifications@github.com:

> Closed #14
> https://github.com/creativecommonskorea/2015-global-summit/issues/14
> via 3b4233e
> https://github.com/creativecommonskorea/2015-global-summit/commit/3b4233ece7965099d57fc66d5cff8a72274d2dcd
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativecommonskorea/2015-global-summit/issues/14#event-422813456
> .

## 

_강현숙  *Jennifer Kang_[image: cckorea_logo3.png]*

 CCKOREA | 사무국장

_Twitter @hskang      Tel_ 070-7618-0321

hskang211@gmail.com

_Address *_마포구 서교동 363-20 5층 \* (오시는길
http://map.naver.com/?dlevel=12&pinType=site&pinId=12231010&x=126.9218731&y=37.5511880&enc=b64
)

_Sites  CCKOREA_ (cc http://cckorea.org/korea.org http://cckorea.org/)*
공유허브 _(_sharehub.kr http://sharehub.kr/_)  *코드나무 *(_codenamu.org
http://codenamu.org/*)

**Comment by khseo** [comment]
Paul Keller 연사소개 변경했습니다:

유럽의 문화 콘텐츠 기관들이 보유한 문화유산을 디지털화해 누구나 열람, 사용할 수 있도록 하는 Europeana의 재단 이사로, 유럽의 저작권 법률의 현대화에 대한 논의에 기여하도록 힘쓰고 있다.
