### ISSUE TITLE
15일 세션 텍스트 수정

### ISSUE THREAD

**Issue by soohyunpae** [creativecommonskorea/2015-global-summit#16]
- 15일 오픈 비즈니스 세션에서 "Paul Stacey_CC 글로벌 오픈 비즈니스 대표"로 수정
- 트랙5. 오픈 글램 -->  "오픈 글램"으로 수정
- 오픈 글램 세션 색상 워크샵 색상(파란색)으로 수정

부탁드려요~! :)

**Comment by mozodev** [comment]
연사 소개는 저렇게 되어 있는데 통일할까요?

```
- name: Paul Stacey
  image: /images/people/1_07_paul-stacey.png
  organize: CC 글로벌 오픈 비즈니스 이니셔티브 담당
```

**Comment by soohyunpae** [comment]
앗 네~ "CC 글로벌 오픈 비즈니스 대표"로 통일해주세요!ㅎ

**Comment by mozodev** [comment]
오픈글램은 이미 강연 형식으로 현재 파란색인데
![2015-10-02 4 06 40](https://cloud.githubusercontent.com/assets/1661950/10241120/9ac468be-691f-11e5-9393-f47b56591032.png)

그 옆에 있는 기술팀같이 워크숍 형식으로 연한 보라색으로 변경할까요?
