### ISSUE TITLE
15일 오픈 비즈니스 수정 Nuno Silva

### ISSUE THREAD

**Issue by soohyunpae** [creativecommonskorea/2015-global-summit#19]
15일 오픈 비즈니스 세션 
Andy Yang --> Nuno Silva 로 수정

**Comment by mozodev** [comment]
Andy Yang_500px CEO 
세션 내용은 그대로고 연사만 바꾸는 건가요? 
연사 소개 원고는 없죠?

**Comment by mozodev** [comment]
> Andy Yang이 아예 못오게 되었데요 ㅡ ㅡ;
> 연사소개에서 이분 사진, 설명 모두 지워주세요....ㅠㅠ
