### ISSUE TITLE
이메일 등록시 영문 안내 번역 필요

### ISSUE THREAD

**Issue by nanshil** [creativecommonskorea/2015-global-summit#3]
현재 이메일 등록을 메일침프로 받고 있어서
등록하면 영문으로 가이드가 나오는데.. 한글로 바꿔줘야할 것 같아요!
그리고 본인 메일로 바로 확인할 수 있게 링크 걸수 없나요? 그게 편리할것 같은데...

하단에 Add us to your address book 다운로드하면 VCF 파일이 나오는데 이건 뭐에요?

![mailchip](https://cloud.githubusercontent.com/assets/11845030/7383843/850b4526-ee61-11e4-8c2f-e10760ffc2e4.jpg)

**Comment by mozodev** [comment]
vcf는 주소록 카드에요. 핸드폰에 추가할 수도 있는...

등록 폼은 수정해봤습니다.
http://eepurl.com/blfugP
