### ISSUE TITLE
모바일 English 링크

### ISSUE THREAD

**Issue by nanshil** [creativecommonskorea/2015-global-summit#4]
모바일에서 CC 로고와 English 버튼이 나란히 떠서 그런지
English 누르면 CC 홈페이지로 이동하네요~
링크 확인 부탁드려요~

모바일에서 텍스트 크기가 다 달라서 정리가 안되어 보이는데..
저만 그런가요?
로고 크기도 좀 줄여야할것 같구요... 
의견 주세요~

**Comment by mozodev** [comment]
일단 링크는 제대로 터치가 되게 분리를 시켜놨고요..

텍스트 크기가 다 다른 건 제목을 이미지로 해서 그런데요... 

해결책은 
1. 이미지 모두 없애고 웹폰트 적용하던가... 

단점: 
- 이미지보다 안 이쁘다... 
- 아래 이미지는 글씨 위에 점이 찍혀 있는데 이런 걸 css로 하려면 골치 아프다..

![중간 영역 제목 이미지](http://summit.cckorea.org/img/mailing-heading.png)
1. 각 해상도별 텍스트 이미지 만들기 - 근데 이건 크기와 꺽이는 지점 등 정확하게 이미지 작업을 해야됨..

**Comment by mozodev** [comment]
참 반응형 화면은 아래 웹사이트에 summit.cckorea.org 넣고 엔터치면 각 화면별로 볼 수 있어요
http://mattkersley.com/responsive/
